on:
  pull_request:
    branches:
    - main
jobs:
  runTest:
    name: Test on pull request.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: SetUp node
      uses: actions/setup-node@v1
    - name: npm install and test
      run: |
        npm install
        cd react-client && npm test
